version: '3.3'
services:
    frontend:
      image: halogendevelopers/halobizfrontend
      container_name: halobiz_frontend
      volumes:
        - halobiz_frontend:/app
      ports:
      - '80'
      healthcheck:
        interval: 20s
        timeout: 10s
        retries: 3

    backend:
      image: halogendevelopers/halobizbackenddev
      environment:
       - DbServer=tcp:halo-biz-db.database.windows.net
       - DbPort=1433
       - DbUser=halobiz
       - DbPassword=A87HBG@#&&&
       - Database=halo-biz-db
       - JWTSecretKey=401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429090fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1
      ports:
       - '80'
      volumes:
       - halobiz_backend.data:/app
      container_name: halobiz_backend
      healthcheck:
        interval: 20s
        timeout: 10s
        retries: 3

volumes:
  halobiz_frontend.data:
  halobiz_backend.data:






