version: "3.1" # version 3.1, to use secret for stack
services:
  psql:
    image: postgres:9.2
    secrets:   # redis cache build for the stack
      - psql_tolu # secret name
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_tolu
      #POSTGRES_USER_FILE: /run/secrets/psql_tolu
secrets: 
  psql_tolu: #secret name 
    external: true
