version: "3" # version 3.1, to use secret for stack
services:

  webapp:
    image: tolucoker/ticket:release-code
    ports:
      - 8000:80
    networks:
      - frontend
    depends_on:
      - psql_db
      - redis-cache
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  redis-cache:   # redis cache build for the stack
    image: redis:6.0.8
    ports:
      - "6739"
    command: >
      sh -c "redis-server  /usr/local/etc/redis/redis.conf"
    networks:
      - frontend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  psql_db:
    image: library/postgres:9.2
    volumes:
      - db-data:/var/lib/postgresql/data # bind mount the volume of the database
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]

networks: #define the network
  frontend:
  backend:
volumes:
  db-data:

