# Generated by Django 3.1 on 2020-09-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Tick box if user is a IT Team', verbose_name='IT Team'),
        ),
    ]
