# Generated by Django 3.1 on 2020-09-23 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='roles_table',
            fields=[
                ('role_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('User', 'User'), ('IT team', 'IT team'), ('Admin', 'Admin')], default='User', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'roles_table',
            },
        ),
        migrations.CreateModel(
            name='permission',
            fields=[
                ('permission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_user', to='request.roles_table')),
                ('user_permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='bio',
            fields=[
                ('bio_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(default='Job Role', max_length=40)),
                ('branch', models.CharField(default='Location', help_text='Branch Location', max_length=20)),
                ('phone', models.CharField(default='Mobile', max_length=12, unique=True)),
                ('department', models.CharField(default='Department', max_length=25)),
                ('bio_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bio_user_relation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bio_table',
            },
        ),
    ]
