# Generated by Django 3.1 on 2020-09-26 21:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bio',
            fields=[
                ('bio_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(blank=True, default='Job Role', max_length=40)),
                ('branch', models.CharField(default='Location', help_text='Location', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=12, unique=True)),
                ('department', models.CharField(default='Department', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Bio_table',
            },
        ),
        migrations.CreateModel(
            name='permission',
            fields=[
                ('permission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='request_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField(default='Raise a request', help_text='Whats your request', max_length=2000)),
                ('request_open', models.DateTimeField(auto_now_add=True)),
                ('request_time_closed', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.CharField(choices=[('Network', 'Network'), ('Email', 'Email'), ('Printer', 'Printer'), ('IP Phone', 'IP Phone'), ('Hardware', 'Hardware'), ('Software', 'Software')], default='Network', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=40)),
                ('copy_team', models.CharField(blank=True, help_text='Copy team members', max_length=40)),
                ('close_request', models.CharField(blank=True, choices=[('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Open', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Request_table',
            },
        ),
        migrations.CreateModel(
            name='response_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(help_text='response to request', max_length=1000)),
                ('first_response', models.DateTimeField(auto_now_add=True)),
                ('later_response', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='roles_table',
            fields=[
                ('role_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('User', 'User'), ('IT team', 'IT team'), ('Admin', 'Admin')], default='User', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'roles_table',
            },
        ),
        migrations.CreateModel(
            name='user_request_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IT_accept', models.BooleanField(default=False)),
                ('request_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_request_link', to='request.request_table')),
            ],
            options={
                'verbose_name_plural': 'User_request_table',
            },
        ),
    ]
