# Generated by Django 3.1.1 on 2020-11-24 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='user_request_table',
            name='user_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request_link', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sla',
            name='sla_priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_priority_table_link', to='request.priority_tables'),
        ),
        migrations.AddField(
            model_name='request_table',
            name='sla_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_sla_request', to='request.sla'),
        ),
        migrations.AddField(
            model_name='permission',
            name='role_permit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_user_role', to='request.roles_table'),
        ),
        migrations.AddField(
            model_name='permission',
            name='user_permit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bio',
            name='bio_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bio_user_relation', to=settings.AUTH_USER_MODEL),
        ),
    ]
