# Generated by Django 3.1 on 2020-09-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles_table',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('IT team', 'IT team'), ('Admin', 'Admin')], default='User', max_length=30),
        ),
    ]
