# Generated by Django 3.1.1 on 2020-11-27 16:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20201124_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom_email_message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assign_email', models.TextField(blank=True, max_length=2000, verbose_name='Type your request assign email to Customers')),
                ('complete_email', models.TextField(blank=True, max_length=2000, verbose_name='Type your request complete email to Customers')),
                ('closed_request_email', models.TextField(blank=True, max_length=2000, verbose_name='Type your request closed email to Customers')),
                ('cancelled_request_email', models.TextField(blank=True, max_length=2000, verbose_name='Type your request cancelled email to Customers')),
            ],
        ),
    ]
