# Generated by Django 3.1.1 on 2020-10-06 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20200926_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='role_permit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_user_role', to='request.roles_table'),
        ),
        migrations.AlterField(
            model_name='request_table',
            name='close_request',
            field=models.CharField(blank=True, choices=[('Closed', 'Closed'), ('Cancelled', 'Cancelled'), ('Open', 'Open')], default='Open', max_length=15),
        ),
    ]
