# Generated by Django 3.1 on 2020-09-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20200923_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles_table',
            name='role',
            field=models.CharField(default='User', max_length=8),
        ),
    ]
