# Generated by Django 3.1.1 on 2020-10-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20201006_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_request_table',
            name='IT_accept',
        ),
    ]
