# Generated by Django 3.1.1 on 2020-11-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_custom_email_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_table',
            name='request_time_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='request_table',
            name='request',
            field=models.TextField(help_text='What is your request?', max_length=2000, verbose_name='Subject'),
        ),
    ]
