# Generated by Django 3.1.1 on 2020-11-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_auto_20201127_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_table',
            name='request_time_started',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='request_table',
            name='close_request',
            field=models.CharField(blank=True, choices=[('Cancelled', 'Cancelled'), ('Open', 'Open'), ('Completed', 'Completed'), ('Started', 'Started')], default='Open', max_length=15),
        ),
    ]
