# Generated by Django 3.1.1 on 2020-10-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_remove_user_request_table_it_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_table',
            name='request',
            field=models.TextField(help_text='What is your request', max_length=2000),
        ),
    ]
