# Generated by Django 3.1.1 on 2020-11-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_auto_20201128_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_table',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='request_table',
            name='close_request',
            field=models.CharField(blank=True, choices=[('Cancelled', 'Cancelled'), ('Open', 'Open'), ('Completed', 'Completed'), ('Started', 'Started'), ('Closed', 'Closed')], default='Open', max_length=15),
        ),
    ]
