# Generated by Django 3.1.1 on 2020-10-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_auto_20201006_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_table',
            name='assigned_to',
            field=models.CharField(blank=True, default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='request_table',
            name='category',
            field=models.CharField(choices=[('Network', 'Network'), ('Email', 'Email'), ('Printer', 'Printer'), ('IP Phone', 'IP Phone'), ('Hardware', 'Hardware'), ('Software', 'Software'), ('Wireless', 'Wireless'), ('Authentication', 'Authentication'), ('Other', 'Other')], default='Network', max_length=20),
        ),
    ]
