# Generated by Django 3.1 on 2020-09-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_auto_20200923_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='branch',
            field=models.CharField(default='Location', help_text='Location', max_length=20),
        ),
        migrations.AlterField(
            model_name='bio',
            name='phone',
            field=models.CharField(blank=True, default='Mobile', max_length=12, unique=True),
        ),
    ]
