# Generated by Django 3.1.1 on 2020-11-30 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_auto_20201130_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response_table',
            old_name='first_response',
            new_name='time_response',
        ),
        migrations.RenameField(
            model_name='response_table',
            old_name='later_response',
            new_name='time_response_update',
        ),
        migrations.AddField(
            model_name='request_table',
            name='request_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_response', to='request.response_table'),
        ),
    ]
