# Generated by Django 3.1 on 2020-09-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0006_auto_20200924_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='job_title',
            field=models.CharField(blank=True, default='Job Role', max_length=40),
        ),
    ]
