# Generated by Django 3.1.1 on 2020-10-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_auto_20201018_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_table',
            name='request_open',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='request_table',
            name='request_time_closed',
            field=models.DateTimeField(null=True),
        ),
    ]
