# Generated by Django 3.1.1 on 2020-12-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_auto_20201130_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response_table',
            name='time_response',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='response_table',
            name='time_response_update',
            field=models.DateTimeField(null=True),
        ),
    ]
