# Generated by Django 3.1 on 2020-09-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0007_auto_20200924_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='phone',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
