# Generated by Django 3.1 on 2020-09-26 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0008_auto_20200924_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField(default='Raise a request', help_text='Whats your request', max_length=3000)),
                ('request_open', models.DateTimeField(auto_now_add=True)),
                ('request_assigned', models.DateTimeField(auto_now=True)),
                ('request_close', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Network', 'Network'), ('Email', 'Email'), ('Printer', 'Printer'), ('IP Phone', 'IP Phone'), ('Hardware', 'Hardware'), ('Software', 'Software')], default='Network', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Request_table',
            },
        ),
        migrations.CreateModel(
            name='user_request_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IT_accept', models.BooleanField(default=False)),
                ('request_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_request_link', to='request.request_table')),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_request_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User_request_table',
            },
        ),
    ]
