# Generated by Django 3.1.1 on 2020-10-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_auto_20201020_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_table',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
