# Generated by Django 3.1.1 on 2020-10-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_request_table_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='sla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla_category', models.CharField(max_length=30, unique=True)),
                ('sla_time', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'SLA',
            },
        ),
    ]
