# Generated by Django 3.1.1 on 2020-11-18 01:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_request_table_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='priority_tables',
            fields=[
                ('priority_pk', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority_field', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='sla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla_category', models.CharField(max_length=30, unique=True)),
                ('sla_time', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'SLA',
            },
        ),
        migrations.RemoveField(
            model_name='request_table',
            name='category',
        ),
        migrations.AlterField(
            model_name='request_table',
            name='close_request',
            field=models.CharField(blank=True, choices=[('Cancelled', 'Cancelled'), ('Open', 'Open'), ('Completed', 'Completed')], default='Open', max_length=15),
        ),
        migrations.AddField(
            model_name='request_table',
            name='sla_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request_sla_request', to='request.sla'),
            preserve_default=False,
        ),
    ]
