# Generated by Django 3.1 on 2020-09-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_request_table_user_request_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_table',
            name='copy_team',
            field=models.CharField(blank=True, help_text='Copy team members', max_length=40),
        ),
    ]
