# Generated by Django 3.1 on 2020-09-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_request_table_copy_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='response_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(help_text='response to request', max_length=1000)),
                ('first_response', models.DateTimeField(auto_now_add=True)),
                ('later_response', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='request_table',
            name='request_assigned',
        ),
        migrations.RemoveField(
            model_name='request_table',
            name='request_close',
        ),
        migrations.AddField(
            model_name='request_table',
            name='close_request',
            field=models.CharField(blank=True, choices=[('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Open', max_length=15),
        ),
        migrations.AddField(
            model_name='request_table',
            name='request_time_closed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='request_table',
            name='request',
            field=models.TextField(default='Raise a request', help_text='Whats your request', max_length=2000),
        ),
    ]
