# Generated by Django 3.1.1 on 2020-10-23 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0011_user_request_table_sla_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_request_table',
            name='sla_request',
        ),
        migrations.AddField(
            model_name='request_table',
            name='sla_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request_sla_request', to='request.sla'),
            preserve_default=False,
        ),
    ]
