# Generated by Django 3.1.1 on 2020-10-25 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0013_auto_20201023_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_table',
            name='category',
        ),
    ]
