# Generated by Django 3.1.1 on 2020-11-18 01:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0014_remove_request_table_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='priority_table',
            fields=[
                ('priority_pk', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority_field', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='request_table',
            name='close_request',
            field=models.CharField(blank=True, choices=[('Cancelled', 'Cancelled'), ('Open', 'Open'), ('Completed', 'Completed')], default='Open', max_length=15),
        ),
    ]
